---
- hosts: localhost
  gather_facts: false
  tasks: 
  - name: print working directory
    shell: pwd 
  - name: run kubernetes.yaml to deploy flask app and create a service
    shell: kubectl apply -f kubernetes.yaml