---
- hosts: localhost
  gather_facts: false
  environment:
     KUBECONFIG:"~/.kube/config"
    # Create Kubernetes resources to run flask app.
  tasks:    
  - name: Deploy my app secrets.
    k8s:
      definition: '{{ item }}'
      kubeconfig: '~/.kube/config'
      state: present
  - name: Create a Deployment for flask app
    k8s:
      state: present
      definition:
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: flaskapp-deployment
          namespace: default
          labels:
            app: flaskapp
        spec:
          selector:
            matchLabels:
              app: flaskapp
          replicas: 3
          template:
            metadata:
              labels:
                app: flaskapp
            spec:
              containers:
              - name: flaskapp
                image: karinegh18/flask-app:latest
                imagePullPolicy: Always
                ports:
                - containerPort: 8383     
          strategy:
             type: RollingUpdate
             rollingUpdate:
               maxSurge: 1
               maxUnavailable: 0
  - name: Create a Service for flask app.
    k8s:
      state: present
      definition:
        apiVersion: v1
        kind: Service
        metadata:
          name: flaskapp-service
          namespace: default
        spec:
          type: NodePort
          selector:
            app: flaskapp
          ports:
          - protocol: TCP
            port: 8383
            targetPort: 8383