- hosts: localhost
  tasks:
    - name: Create a k8s namespace
      community.kubernetes.k8s:  
        name: flask
        api_version: v1
        kind: Namespace
        state: present

# Passing the object definition from a file

    - name: Create a Deployment and service by reading the definition from a local file
      community.kubernetes.k8s:
        state: present
        src: ./kubernetes.yaml
