---
- hosts: localhost
  tasks:
    - name: use cluster
      command: kubectl cluster-info --context kind-app 
      become: True
      become_user: sysadmin
    - name: run kubernetes.yaml to deploy flask app and create a service
      command: kubectl apply -f kubernetes.yaml
      become: True
      become_user: sysadmin